apiVersion: v1
kind: Pod
metadata:
  name: gourmand
  labels:
    app.kubernetes.io/name: experience
spec:
  restartPolicy: Never
  containers:
    - name: python
      image: python:3.12-alpine
      command: ["python", "-c", "import time; time.sleep(5); data = bytearray(256 * 1024 * 1024); time.sleep(60)"]
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 250m
          memory: 64Mi